// Game Loop Slice - Управление игровым временем и событиями
import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface GameLoopState {
  isRunning: boolean;
  currentTime: number; // timestamp
  gameSpeed: number; // 1x, 2x, 4x speed
  lastEventTime: number;
  eventInterval: number; // milliseconds between events
  currentEvent: GameEvent | null;
}

interface GameEvent {
  id: string;
  title: string;
  description: string;
  choices: EventChoice[];
  timestamp: number;
}

interface EventChoice {
  id: string;
  text: string;
  effects: {
    health?: number;
    happiness?: number;
    wealth?: number;
    energy?: number;
  };
}

const initialState: GameLoopState = {
  isRunning: false,
  currentTime: Date.now(),
  gameSpeed: 1,
  lastEventTime: Date.now(),
  eventInterval: 15000, // 15 seconds between events for testing
  currentEvent: null,
};

const gameLoopSlice = createSlice({
  name: 'gameLoop',
  initialState,
  reducers: {
    startGameLoop: (state) => {
      state.isRunning = true;
      state.currentTime = Date.now();
      state.lastEventTime = Date.now();
    },
    
    stopGameLoop: (state) => {
      state.isRunning = false;
    },
    
    setGameSpeed: (state, action: PayloadAction<number>) => {
      state.gameSpeed = Math.max(1, Math.min(action.payload, 4));
    },
    
    tick: (state) => {
      if (!state.isRunning) return;
      
      const now = Date.now();
      const deltaTime = (now - state.currentTime) * state.gameSpeed;
      state.currentTime = now;
      state.lastEventTime += deltaTime;
      
      // Check if should generate new event
      if (state.lastEventTime >= state.eventInterval && !state.currentEvent) {
        state.lastEventTime = 0;
        // Event will be generated by async thunk
      }
    },
    
    generateEvent: (state, action: PayloadAction<GameEvent>) => {
      state.currentEvent = action.payload;
    },
    
    resolveEvent: (state, action: PayloadAction<string>) => {
      if (!state.currentEvent) return;
      
      const choice = state.currentEvent.choices.find(c => c.id === action.payload);
      if (choice) {
        // Apply effects to character stats (handled by character slice)
        state.currentEvent = null;
        state.lastEventTime = Date.now();
      }
    },
    
    skipEvent: (state) => {
      state.currentEvent = null;
      state.lastEventTime = Date.now();
    },
  },
});

export const {
  startGameLoop,
  stopGameLoop,
  setGameSpeed,
  tick,
  generateEvent,
  resolveEvent,
  skipEvent,
} = gameLoopSlice.actions;

export default gameLoopSlice.reducer;
